//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeachersDiary.Clients.Mvc.Translations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Андриян Кръстев.
        /// </summary>
        public static string AndriyanKrastevLabel {
            get {
                return ResourceManager.GetString("AndriyanKrastevLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класове.
        /// </summary>
        public static string ClassesLabel {
            get {
                return ResourceManager.GetString("ClassesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при създаването на клас. Моля свържете се със училищният администратор!.
        /// </summary>
        public static string ErrorOnCreationOfNewClass {
            get {
                return ResourceManager.GetString("ErrorOnCreationOfNewClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати файл.
        /// </summary>
        public static string FileSentLabel {
            get {
                return ResourceManager.GetString("FileSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден файл формат!.
        /// </summary>
        public static string IncorrectFileFormat {
            get {
                return ResourceManager.GetString("IncorrectFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден имейл или парола..
        /// </summary>
        public static string IncorrentEmailOrPasswordMessage {
            get {
                return ResourceManager.GetString("IncorrentEmailOrPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LogInLabel {
            get {
                return ResourceManager.GetString("LogInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string LogOffLabel {
            get {
                return ResourceManager.GetString("LogOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов профил.
        /// </summary>
        public static string NewProfileLabel {
            get {
                return ResourceManager.GetString("NewProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друго.
        /// </summary>
        public static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля изберете учител.
        /// </summary>
        public static string PleaseSelectClassTeacher {
            get {
                return ResourceManager.GetString("PleaseSelectClassTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете училище.
        /// </summary>
        public static string SelectSchool {
            get {
                return ResourceManager.GetString("SelectSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string SignUpLabel {
            get {
                return ResourceManager.GetString("SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ученици.
        /// </summary>
        public static string StudentLabel {
            get {
                return ResourceManager.GetString("StudentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учителски дневник.
        /// </summary>
        public static string TeachersDiaryTitle {
            get {
                return ResourceManager.GetString("TeachersDiaryTitle", resourceCulture);
            }
        }
    }
}
