// <auto-generated />
namespace TeachersDiary.Data.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddApplicationRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddApplicationRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201706102045287_AddApplicationRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
